# This is a basic workflow to help you get started with Actions

name: NPM Version

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Node Environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          
      # Bump Package Version
      - name: Automated Version Bump
        # You may pin to the exact commit or the version.
        # uses: phips28/gh-action-bump-version@92eef6faf8f8d95f75486e2b2aded91d3cfe0e0e
        uses: phips28/gh-action-bump-version@v9.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
